name: Redis Service Example
on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    # Docker Hub container that `container-job` runs in
    container: node:10.16-buster

    # Service containers to run with the `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v1

      - name: Run CI
        run: npm CI
        working-directory: ./redis

      - name: Connect to Redis
        run: node client.js
        working-directory: ./redis
        env:
          REDIS_HOST: redis
          # The
          #REDIS_PORT: ${{ job.services.redis.ports[6379] }}

  vm-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp

    steps:
    - uses: actions/checkout@v1

    - run: npm ci
      working-directory: ./redis

    - run: node client.js
      working-directory: ./redis
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
