name: Redis Service Example
on: push

jobs:

  vm-job:
    # Use the latest version of the GitHub-hosted ubuntu environment
    runs-on: ubuntu-latest

    # Service containers to run with the `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        #
        ports:
          # Opens port 6379 on the host and container
          - 6379:6379

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v1

      - name: Run CI
        run: npm ci
        working-directory: ./redis

      - name: Connect to Redis
        run: node client.js
        working-directory: ./redis
        env:
          # Default Redis host is localhost
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
