name: Redis Service Example
on: push

jobs:
  container-job:
    # Use the latest version of the GitHub-hosted ubuntu environment
    runs-on: ubuntu-latest
    # Docker Hub container that `container-job` runs in
    container: node:10.16-buster

    # Service containers to run with the `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v1

      - name: Run CI
        run: npm ci
        working-directory: ./redis

      - run: |
        echo Host: $REDIS_HOST
        echo Port: $REDIS_PORT

      - name: Connect to Redis
        run: node client.js
        working-directory: ./redis
        env:
          # The default Redis host is localhost, use Docker host name
          REDIS_HOST: redis

      - run: |
        echo Host: $REDIS_HOST
        echo Port: $REDIS_PORT

  vm-job:
    # Use the latest version of the GitHub-hosted ubuntu environment
    runs-on: ubuntu-latest

    # Service containers to run with the `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        #
        ports:
          - 6379

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v1

      - name: Run CI
        run: npm ci
        working-directory: ./redis

      - run: |
        echo Host: $REDIS_HOST
        echo Port: $REDIS_PORT

      - name: Connect to Redis
        run: node client.js
        working-directory: ./redis
        env:
          # Default Redis host is localhost
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}

      - run: |
        echo Host: $REDIS_HOST
        echo Port: $REDIS_PORT
